-- liquibase formatted sql

-- changeset ken:1658410379859-1
CREATE TABLE "users" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(255), "password_hash" VARCHAR(255), "password_salt" VARCHAR(255), CONSTRAINT "users_pkey" PRIMARY KEY ("id"));

